package Main.Graphics;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import Main.Bank.BankAccount;
import Main.Bank.Transaction;
import Main.Bank.TransactionType;

import javax.swing.*;

/**
 *
 * @author erfan
 */
public class BankAccountMenu extends javax.swing.JFrame implements Runnable {

    BankAccount account ;
    boolean exit = false;

    /**
     * Creates new form BankAccountMenu
     */
    public BankAccountMenu(BankAccount account) {
        this.account = account;
        initComponents();
        setVisible(true);

        Thread t =new Thread(this);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
    moneyAmount = new javax.swing.JSpinner();
    dispositButton = new javax.swing.JButton();
    withdrawalButton = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    transactionArea = new javax.swing.JTextArea();
    jLabel2 = new javax.swing.JLabel();
    balanceLabel = new javax.swing.JLabel();
    exitButton = new javax.swing.JButton();

    setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setText("Money :");

        moneyAmount.setValue(10);

        dispositButton.setText("Disposit");
        dispositButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            dispositButtonActionPerformed(evt);
        }
    });

        withdrawalButton.setText("Withdrawal");
        withdrawalButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            withdrawalButtonActionPerformed(evt);
        }
    });

        transactionArea.setBackground(new java.awt.Color(60, 63, 65));
        transactionArea.setColumns(20);
        transactionArea.setForeground(new java.awt.Color(51, 255, 51));
        transactionArea.setRows(5);
        jScrollPane1.setViewportView(transactionArea);

        jLabel2.setText("Balance :");

        balanceLabel.setText("None");

        exitButton.setBackground(new java.awt.Color(255, 0, 0));
        exitButton.setForeground(new java.awt.Color(204, 0, 0));
        exitButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            exitButtonActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(balanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(moneyAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dispositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(withdrawalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
            );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(balanceLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dispositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(moneyAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(withdrawalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            );

    pack();
}// </editor-fold>



    private void dispositButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int money = (int)moneyAmount.getValue();

        Transaction t = new Transaction(money , TransactionType.DEPOSIT);
        account.performTransaction(t);



    }

    private void withdrawalButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        int money = (int)moneyAmount.getValue();

        Transaction t = new Transaction(money , TransactionType.WITHDRAW);
        account.performTransaction(t);

    }




    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        exit = true;

        dispose();
    }


    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JButton dispositButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner moneyAmount;
    private javax.swing.JTextArea transactionArea;
    private javax.swing.JButton withdrawalButton;
    // End of variables declaration


    @Override
    public void run(){

        while (! exit){

            balanceLabel.setText( String.valueOf( account.getAccountBalance() ) );

            String str = "";

             for (Transaction a : account.getAccountTransactions()){
                str += a.showInfo();
                str += "\n";
        }

        transactionArea.setText(str);

            try {
                Thread.sleep(200);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }

        }


    }
}
