package Main.Graphics;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author erfan
 */
public class CountryMenu extends javax.swing.JFrame {

    /**
     * Creates new form CountryMenu
     */
    public CountryMenu() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buildCity = new javax.swing.JButton();
        enterToCity = new javax.swing.JButton();
        citiesInfo = new javax.swing.JButton();
        countryInfo = new javax.swing.JButton();
        financialMng = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buildCity.setText("Build New City");
        buildCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildCityActionPerformed(evt);
            }
        });

        enterToCity.setText("Enter To A City");
        enterToCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterToCityActionPerformed(evt);
            }
        });

        citiesInfo.setText("Cities Information");
        citiesInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citiesInfoActionPerformed(evt);
            }
        });

        countryInfo.setText("Country Information");
        countryInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryInfoActionPerformed(evt);
            }
        });

        financialMng.setText("Financial Management");
        financialMng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                financialMngActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(59, 59, 59)
                                                .addComponent(buildCity, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(57, 57, 57)
                                                .addComponent(enterToCity, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(59, 59, 59)
                                                .addComponent(countryInfo))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(154, 154, 154)
                                                .addComponent(citiesInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(64, 64, 64)
                                                .addComponent(financialMng)))
                                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(countryInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(buildCity, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(enterToCity, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(financialMng, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(citiesInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>



    private void buildCityActionPerformed(java.awt.event.ActionEvent evt) {
        new BuildCity();
    }

    private void enterToCityActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        new EnterToCity();
    }

    private void countryInfoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        new CountryInfo();
    }

    private void citiesInfoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        new CitiesInfo();
    }

    private void financialMngActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        new financialMng();
    }




    // Variables declaration - do not modify
    private javax.swing.JButton buildCity;
    private javax.swing.JButton citiesInfo;
    private javax.swing.JButton countryInfo;
    private javax.swing.JButton enterToCity;
    private javax.swing.JButton financialMng;
    // End of variables declaration
}

