package Main.Graphics;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import Main.Building.Bus_Terminal;
import Main.Building.Terminal;
import Main.Main;
import Main.Person;
import javax.swing.*;
import java.util.ArrayList;

/**
 *
 * @author erfan
 */
public class EngagePerson <T extends  Terminal> extends javax.swing.JFrame {


    String job ;
    ArrayList<T> terminals;
    Person person = null ;
    Terminal terminal;


    DefaultListModel<String> dlm1 = new  DefaultListModel<>();
    DefaultListModel<String> dlm2 = new  DefaultListModel<>();

    void setDlm1(){

        for (Terminal a : this.terminals)
            dlm1.addElement(a.getTerminalName());


    }

    void setDlm2(){
        dlm2.removeAllElements();
        for (Person a : Main.selectedCity.getPersonList()) {

            if (a.getJob().equals(this.job) && ! a.getHired() )
                dlm2.addElement(String.valueOf(a.getID()));

        }
    }

    /**
     * Creates new form EngagePerson
     */
    public EngagePerson(String job , ArrayList<T> terminals) {
        this.terminals = terminals;
        this.job = job;
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        setDlm1();
        setDlm2();
        jScrollPane1 = new javax.swing.JScrollPane();
        peopleList = new javax.swing.JList<>(dlm2);
        jScrollPane2 = new javax.swing.JScrollPane();
        terminalList = new javax.swing.JList<>(dlm1);
        jLabel1 = new javax.swing.JLabel();
        salaryLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hiredPeopleLabel = new javax.swing.JLabel();
        selectPerson = new javax.swing.JButton();
        selectTerminal = new javax.swing.JButton();
        engageButton = new javax.swing.JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

//        peopleList.setModel(new javax.swing.AbstractListModel<String>() {
//            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
//            public int getSize() { return strings.length; }
//            public String getElementAt(int i) { return strings[i]; }
//        });
        jScrollPane1.setViewportView(peopleList);

//        terminalList.setModel(new javax.swing.AbstractListModel<String>() {
//            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
//            public int getSize() { return strings.length; }
//            public String getElementAt(int i) { return strings[i]; }
//        });
        jScrollPane2.setViewportView(terminalList);

        jLabel1.setText("Salary :");

        salaryLabel.setText("None");

        jLabel3.setText("Hired " + job + " :");

        hiredPeopleLabel.setText("None");

        selectPerson.setText("Select Peroson");
        selectPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectPersonActionPerformed(evt);
            }
        });

        selectTerminal.setText("Select Terminal");
        selectTerminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectTerminalActionPerformed(evt);
            }
        });

        engageButton.setText("Engage");
        engageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(selectPerson, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(salaryLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(selectTerminal, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane2))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33)
                                                .addComponent(hiredPeopleLabel))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(414, 414, 414)
                                                .addComponent(engageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(64, 64, 64)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane1)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(169, 169, 169)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(salaryLabel))))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(selectPerson)
                                        .addComponent(selectTerminal))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(hiredPeopleLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                .addComponent(engageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>

    private void selectPersonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        person = Person.find_Person_from_ID(Integer.valueOf(peopleList.getSelectedValue()));
        salaryLabel.setText(String.valueOf( person.getSalary() ));
    }

    private void selectTerminalActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        terminal = Terminal.getTerminalByName( terminalList.getSelectedValue() );

        if (job.equals("employee"))
            hiredPeopleLabel.setText(String.valueOf(terminal.number_of_hired_employees()));
        else
            hiredPeopleLabel.setText(String.valueOf( terminal.getDriversList().size() ));


    }


    private void engageButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        try {
            Person.engage(person.getID());

            if (job.equals("employee"))
                terminal.addEmployees(person);
            else
                terminal.add_Driver(person);

            Main.selectedCity.withdrawalBudget(person.getSalary());

        }
        catch (NullPointerException ex){
            ex.printStackTrace();
        }


        if (job.equals("employee"))
            hiredPeopleLabel.setText(String.valueOf(terminal.number_of_hired_employees()));
        else
            hiredPeopleLabel.setText(String.valueOf( terminal.getDriversList().size() ));


        person = null;
        setDlm2();
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify
    private javax.swing.JButton engageButton;
    private javax.swing.JLabel hiredPeopleLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> peopleList;
    private javax.swing.JLabel salaryLabel;
    private javax.swing.JButton selectPerson;
    private javax.swing.JButton selectTerminal;
    private javax.swing.JList<String> terminalList;
    // End of variables declaration
}



//===============================================================================================



