package Main.Graphics;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import Main.Bank.BankAccount;
import Main.Country;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author erfan
 */
public class financialMng extends javax.swing.JFrame implements Runnable {

    boolean exit = false;

    static String logText = "";

    public static void addLog(String msg){
        logText += msg+"\n";
    }

    /**
     * Creates new form financialMng
     */
    public financialMng() {
        initComponents();
        setVisible(true);
        BankAccount.showLog = true;
        Thread t = new Thread(this);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        exitButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        log = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        budgetLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bankMoneyLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);

        exitButton.setBackground(new java.awt.Color(255, 51, 0));
        exitButton.setForeground(new java.awt.Color(255, 51, 0));
        exitButton.setText(" ");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        log.setBackground(new Color(67, 58, 58));
        log.setEditable(false);
        log.setColumns(20);
        log.setForeground(new java.awt.Color(102, 255, 102));
        log.setRows(5);
        jScrollPane1.setViewportView(log);

        jLabel1.setText("Budget :");

        budgetLabel.setText("jLabel2");

        jLabel3.setText("Bank :");

        bankMoneyLabel.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(budgetLabel)
                                                .addGap(125, 125, 125)
                                                .addComponent(jLabel3)
                                                .addGap(33, 33, 33)
                                                .addComponent(bankMoneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                                                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane1))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1)
                                        .addComponent(budgetLabel)
                                        .addComponent(jLabel3)
                                        .addComponent(bankMoneyLabel))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>



    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        exit = true;
        logText = "";
        BankAccount.showLog = false;
        dispose();
    }




    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify
    private javax.swing.JLabel bankMoneyLabel;
    private javax.swing.JLabel budgetLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea log;
    // End of variables declaration


    @Override
    public void run(){

        budgetLabel.setText(String.valueOf(Country.totalBudget()));

        while (! exit){

            bankMoneyLabel.setText(String.valueOf(Country.getTotalMoneyInBanks()));
            log.setText(this.logText);

            try {
                Thread.sleep(300);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }

        }
    }
}
