package Main.Graphics;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import Main.Building.Terminal;
import Main.Main;

import javax.swing.*;

/**
 *
 * @author erfan
 */
public class JourneyHistory extends javax.swing.JFrame {

    DefaultListModel<String> dlm = new DefaultListModel<>();

    void setDlm(){

        for(Terminal t : Main.selectedCity.getAllTerminals() )
            dlm.addElement(t.getTerminalName());

    }

    /**
     * Creates new form JourneyHistory
     */
    public JourneyHistory() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        setDlm();
        jScrollPane1 = new javax.swing.JScrollPane();
        terminalList = new javax.swing.JList<>(dlm);
        startingButton = new javax.swing.JButton();
        destinationButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        historyBox = new javax.swing.JTextArea();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

//        terminalList.setModel(new javax.swing.AbstractListModel<String>() {
//            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
//            public int getSize() { return strings.length; }
//            public String getElementAt(int i) { return strings[i]; }
//        });
        jScrollPane1.setViewportView(terminalList);

        startingButton.setText("Starting Point Of Journey");
        startingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startingButtonActionPerformed(evt);
            }
        });

        destinationButton.setText("Destination Point Of Journey");
        destinationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinationButtonActionPerformed(evt);
            }
        });

        historyBox.setColumns(20);
        historyBox.setRows(5);
        jScrollPane2.setViewportView(historyBox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(startingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(destinationButton, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(startingButton)
                                                .addGap(18, 18, 18)
                                                .addComponent(destinationButton))
                                        .addComponent(jScrollPane2))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>



    private void startingButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        Terminal terminal = Terminal.getTerminalByName(terminalList.getSelectedValue());

        String str = terminal.journeyHistory(true , false);

        historyBox.setText(str);

    }

    private void destinationButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        Terminal terminal = Terminal.getTerminalByName(terminalList.getSelectedValue());

        String str = terminal.journeyHistory(false , true);

        historyBox.setText(str);


    }


    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify
    private javax.swing.JButton destinationButton;
    private javax.swing.JTextArea historyBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton startingButton;
    private javax.swing.JList<String> terminalList;
    // End of variables declaration
}

