package Main.Graphics;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import Main.Main;
import Main.Person;

import javax.swing.*;

/**
 *
 * @author erfan
 */
public class PopulationStatusPage extends javax.swing.JFrame {

    /**
     * Creates new form PopulationStatusPage
     */
    public PopulationStatusPage() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel1.setText("People List :");

        jTextArea1.setText(getStatus());
        jTextArea2.setText(getPeopleList());


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration



    String getStatus(){



        String str = "Your city population : " + Main.selectedCity.getPersonList().size()
                + "\nYour city has " + Person.number_of_jobs("pilot" , Main.selectedCity.getPersonList()) + " pilot(s)"+
                "\nYour city has " + Person.number_of_jobs("driver" , Main.selectedCity.getPersonList()) + " driver(s)"  +
                "\nYour city has " + Person.number_of_jobs("sailor" , Main.selectedCity.getPersonList()) + " sailor(s)" +
                "\nYour city has " + Person.number_of_jobs("sailor" , Main.selectedCity.getPersonList()) + " sailor(s)" +
                "\nYour city has " + Person.number_of_jobs("locomotive driver" , Main.selectedCity.getPersonList()) + " locomotive driver(s)" +
                "\nYour city has " + Person.number_of_jobs("flight attendant" , Main.selectedCity.getPersonList()) + " flight attendant(s)" +
                "\nYour city has " + Person.number_of_jobs("employee" , Main.selectedCity.getPersonList()) + " employee(s)" ;


        return str;

    }

    String getPeopleList(){

        String str = "";

        int counter =0;
        for (Person a : Main.selectedCity.getPersonList()) {

            if (counter % 6 == 0)
                str +="\n";

            str += a.getID() + " - ";

            counter ++;
        }


        return str;

    }
}

